Fix TestAutonaming flakiness (#1984)
`TestAutonaming` occasionally fails if test runs are running within 1
minute of each other because SQS does not allow recreating a deleted
queue within 60s:
```
          aws-native:sqs:Queue (queue):
            error: creating resource: creating resource (await): operation CREATE failed with "Throttling": You must wait 60 seconds after deleting a queue before you can create another with the same name. (Service: Sqs, Status Code: 400, Request ID: 7503e9ea-2fa2-5fba-b1cc-b6117f9af4d4)
```

To fix this I added some random parts to the resource name

Fixes https://github.com/pulumi/pulumi-aws-native/issues/1983